Fixed a bug where an error could be thrown due to an empty XML string.
Error: DOMDocument::loadXML(): Empty string supplied as input.

Occurred when creating a new transaction based on an account credit.